config/routes.rb
Omr::Application.routes.draw do

  get "user/show"

  resources :pins
  resources :approval

  get 'approved' => 'approval#approved'

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}, controllers: {omniauth_callbacks: "omniauth_callbacks"}

  devise_for :users

  match 'users/:id' => 'user#show', as: :user

  get 'about' => 'pages#about'
  get 'index_user' => "pins#index_user"
  root :to => 'pins#index'

end

app/models/pin.rb
class Pin < ActiveRecord::Base
  attr_accessible :description, :image, :image_remote_url
  attr_accessible :pin

  #validates :description, presence: true, length: { less_than: 255 }
  validates :description, presence: true
  validates :user_id, presence: true
  validates_attachment :image, presence: true,
  		     										 content_type: { content_type: ['image/jpeg', 'image/jpg', 'image/png', 'image/gif'] },
  		     										 size: { less_than: 5.megabytes }
  #Has only ONE user and validates that it HAS a user to save to the database.
  #Attach mp3 file.
  #validates_attachment_content_type :mp3, :content_type => [ 'application/mp3','application/x-mp3', 'audio/mpeg', 'audio/mp3' ],
            #:message => 'Please select a .mp3 file'

  belongs_to :user
  has_attached_file :image, styles: { medium: "320x240>"}
  #has_attached_file :mp3
  #has_attached_file :image, :storage => :s3, :s3_credentials => S3_CREDENTIALS, styles: { medium: "320x240>"}

  def image_remote_url=(url_value)
    self.image = URI.parse(url_value) unless url_value.blank?
    super
  end
end

app/models/profile.rb
# *** One user profile
class Profile < ActiveRecord::Base
  attr_accessible :first_name, :last_name 
  #belongs_to :user, :user_id
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :omniauthable, #:recoverable, 
         :rememberable, :trackable, :validatable, :omniauth_providers => [:twitter]

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :profile_attributes, :name, :username, :admin
  
  validates_presence_of :username
  validates_uniqueness_of :username

  extend FriendlyId
  #friendly_id :username, use: :slugged
  friendly_id :name, use: :slugged

  has_many :pins
   
  # *** One user profile
  has_one :profile

    # *** One user profile
  accepts_nested_attributes_for :profile

  def self.from_omniauth(auth)
    where(auth.slice(:provider, :uid)).first_or_create do |user|
      user.provider = auth.provider
      user.uid = auth.uid
      user.username = auth.info.nickname
      user.name = auth.info.nickname
    end
  end
  
  def self.new_with_session(params, session)
    if session["devise.user_attributes"]
      new(session["devise.user_attributes"], without_protection: true) do |user|
        user.attributes = params
        user.valid?
      end
    else
      super
    end
  end

  def password_required?
    super && provider.blank?
  end  

  def update_with_password(params, *options)
    if encrypted_password.blank?
      update_attributes(params, *options)
    else
      super
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/approval_controller.rb
class ApprovalController < ApplicationController
  before_filter :authenticate_user!
  before_filter do
    redirect_to home_path unless user_signed_in? && current_user.admin?
  end

  def approved
    @pins = Pin.where(approved: true).order("created_at desc")
  end

  def index
    @pin = Pin.order("created_at desc")
  end

  def edit
    @pin = Pin.find(params[:id])
  end

  def show
    @pin = Pin.find(params[:id])
  end

  def update
    @pin = Pin.find(params[:id])

    respond_to do |format|
      if @pin.update_attributes(params[:pin])
        format.html { redirect_to approval_index_path, notice: 'Approved' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/omniauth_callbacks_controller.rb
class OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def all
  	#raise request.env["omniauth.auth"].to_yaml
    user = User.from_omniauth(request.env["omniauth.auth"])
    if user.persisted?
      flash.notice = "Signed in!"
      sign_in_and_redirect user
    else
      session["devise.user_attributes"] = user.attributes
      redirect_to new_user_registration_url
    end
  end
  alias_method :twitter, :all
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @pins = Pin.where(approved: true).order("updated_at desc").page(params[:page]).per_page(20)
    @admin = user_signed_in?&&current_user.admin?
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pins }
      format.js #home js for endless scroll
    end
  end

  def about
  end

end

# class PagesController < ApplicationController
#   def home
#   	#rules
#   	@pins = Pins.where(approved: true).order("updated_at desc")
# 		@admin = user_signed_in?&&current_user_admin?
#   end

#   def about
#   	#rules
#   end
# end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  #Allows users to view all pin. 
  before_filter :authenticate_user!, except: [:index, :show]

  #Allows users to only view pins AFTER they login 
  #before_filter :authenticate_user!, except: [:index]

  # GET /pins
  # GET /pins.json
  def index
    @pins = Pin.order("created_at desc").page(params[:page]).per_page(20)
    #@pins = Pin.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pins }
      format.js
    end
  end

  def index_user

    @pins = current_user.pins

    respond_to do |format|
      format.html # index_user.html.erb
      format.json { render json: @pins }
    end
  end

  def any_user

    @user = User.find(params[:id])
    @pins = @user.pins.all

    respond_to do |format|
      format.html # index_user.html.erb
      format.json { render json: @pins }
      format.js
    end
  end

  # GET /pins/1
  # GET /pins/1.json
  def show
    @pin = Pin.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/new
  # GET /pins/new.json
  def new
    # @pin = Pin.new
    @pin = current_user.pins.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @pin }
    end
  end

  # GET /pins/1/edit
  def edit
    # @pin = Pin.find(params[:id])
    @pin = current_user.pins.find(params[:id])
  end

  # POST /pins
  # POST /pins.json
  def create
    # @pin = Pin.new(params[:pin])

    @pin = current_user.pins.new(params[:pin])

    respond_to do |format|
      if @pin.save
        format.html { redirect_to @pin, notice: 'Pin was successfully created.' }
        format.json { render json: @pin, status: :created, location: @pin }
      else
        format.html { render action: "new" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /pins/1
  # PUT /pins/1.json
  def update
    # @pin = Pin.find(params[:id])
    @pin = current_user.pins.find(params[:id])

    respond_to do |format|
      if @pin.update_attributes(params[:pin])
        format.html { redirect_to @pin, notice: 'Pin was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1
  # DELETE /pins/1.json
  def destroy
    # @pin = Pin.find(params[:id])
    @pin = current_user.pins.find(params[:id])
    @pin.destroy

    respond_to do |format|
      format.html { redirect_to pins_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/user_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @pins = @user.pins.page(params[:page]).per_page(5)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pins }
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/omniauth_callbacks_helper.rb
module OmniauthCallbacksHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/approval/_approval.html.erb
<div class="box">
  <%= link_to (image_tag pin.image, width: "40px"), edit_approval_path(pin) %>
  <p class="description">
    <%= pin.description %>
  </p>
  <p>
    <strong>
      Spotted by <%= pin.user.name %>
    </strong>
  </p>
  <% if pin.approved? %>
    <div class="approved">
      <p>
        Approved
      </p>
    </div>
  <% else %>
    <div class="approval">
      <p>
        Needs approval: <%= link_to 'Approve?', edit_approval_path(pin) %>
      </p>
    </div>
    
  <% end %>
</div>

app/views/approval/_form.html.erb
<%= simple_form_for(@pin, :url => approval_path, html: { class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>
  <%= f.full_error :image_file_size, class: "alert alert-error" %>
  <%= f.full_error :image_content_type, class: "alert alert-error" %>

  <p>
  	<%= image_tag @pin.image %>
  </p>
  <p>
  	<%= @pin.description %>
  </p>
  <p>
  	By checking this box you approve this image and post. 
  	<%= f.check_box :approved, {}, 'true', 'false' %>
  </p>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/approval/approved.html.erb
<div>
	<h3> Your job is only to approve this post</h3>
</div>

<div id="pins">
  <%= render partial: 'approval', collection: @pins, as: :pin %>
</div>

app/views/approval/edit.html.erb
<h1>Editing pin</h1>
<%= render 'form' %>

<%= link_to 'Back', approval_index_path %>

app/views/approval/index.html.erb
<div id="pins">
	<%= render partial: 'approval', collection: @pins, as: :pin %>
</div>	

app/views/approval/show.html.erb
<div class="row">
	<div class="span6 offset3">
		<div class="well">
			<%= image_tag @pin.image %>
			<p>
			  <%= @pin.description %>
			</p>
			<p>
			  <%= @pin.user.name %>
			</p>	
		</div>
	</div>
</div>

app/views/layouts/_footer.html.erb
<div class="footer">
	<small>
		<%= link_to "One Month Rails", "http://onemonthrails.com" %> 
		by <%= link_to "Mattan Griffel", "http://mattangriffel.com"%>
	</small>
</div>

app/views/layouts/_header.html.erb
<div class="navbar navbar-fixed-top">
 <div class="navbar-inner">
  <div class="container">
    <!-- .btn-navbar is used as the toggle for collapsed navbar content -->
    <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </a>
    <!-- Be sure to leave the brand out there if you want it shown -->
    <%= link_to "One Month Rails", root_path, class: "brand" %>
    <!-- Everything you want hidden at 940px or less, place within here -->
    <div class="nav-collapse collapse">
    	 <ul class="nav">
      	<li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
      </ul>
      <ul class="nav pull-right">
        <% if @admin = user_signed_in?&&current_user.admin?%>
            <li><%= link_to "Admin", approval_index_path %></li>
            <%else%>
        <%end%>
        <% if user_signed_in?%>
          <li><%= link_to "Add Pin", new_pin_path %></li>
          <li><%= link_to 'My Pins', index_user_path %><li>
          <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
          <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
        <%else%>
          <li><%= link_to "Login", new_user_session_path %></li>
          <li><%= link_to "Sign in with Twitter", user_omniauth_authorize_path(:twitter) %></li>
        <%end%>
      </ul>
     </div>
   </div>
 </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>One Month Rails</title>
	  <%= stylesheet_link_tag    "application", :media => "all" %>
	  <%= javascript_include_tag "application" %>
	  <%= csrf_meta_tags %>
	</head>
	<body>
		<%= render 'layouts/header' %>
		<div class="container">
			<% flash.each do |name, msg| %>
					<%= content_tag(:div, msg, class: "alert alert-#{name}") %>
			<% end %>
			<%= yield %>
			</div>
			<!-- Create another container -->
			<div class="footer">
				<footer>
				<%= render 'layouts/footer' %>
				</footer>
		</div>
	</body>
</html>

app/views/pages/_home.html.erb
<% if user_signed_in?%>
  <h1> <%=current_user.name%> You're logged in!</h1>
<%else%>
  <div class="hero-unit">
		<h1>Welcome to One Month Rails!</h1>
		<p>
			You've found the home page for the
			<%= link_to "One Month Rails", "http://onemonthrails.com" %>
			application.
			</p>
		<p>
			<%= link_to "Sign Up Now!", new_user_registration_path, class: "btn btn-primary btn-large" %>
		</p>
	</div>
<%end%>

app/views/pages/about.html.erb
<h1>About</h1>
<p>
	<%= link_to "One Month Rails", "http://onemonthrails.com" %>
	is a project to teach 
	<%= link_to "Ruby on Rails", "http://rubyonrails.org" %>
	in one month. This is the sample applicaion.
</p>

app/views/pins/_form.html.erb
<%= simple_form_for(@pin, html: {class: "form-horizontal"}) do |f| %>
  <%= f.error_notification %>
  <%= f.full_error :image_file_size, class: "alert alert-error" %>
  <%= f.full_error :image_content_type, class: "alert alert-error" %>

	<%= f.input :image, label: "Upload an image" %>
	<%= f.input :image_remote_url, label: "or enter a URL" %>
  <%= f.input :description, as: :text, input_html: { rows: "3" } %>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-primary" %>
  </div>
<% end %>

app/views/pins/_pin.html.erb
<div class="box">
	<%= link_to (image_tag pin.image(:medium)), pin %>
	<p class="description">
		<%= pin.description %>
	</p>
	<p>
		<strong>
			<!-- Posted by <%= pin.user.name %> -->
			Posted by <%= link_to pin.user.name, pin.user %>
		</strong>
	</p>
	<p class="time">
		Poated @ <%= pin.created_at %>
	</p>
	<% if current_user == pin.user %>
	</br>
	  <p>
		  <%= link_to 'Edit', edit_pin_path(pin) %>
		  <%= link_to 'Destroy', pin, method: :delete, data: { confirm: 'Are you sure you want to delete this?' } %>
		</p>
	<% end %>
</div>

app/views/pins/any_user.erb
<%= render 'pages/home' %>

<div id="pins">
  <%= render @pins %>
</div>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render 'form' %>

<%= link_to 'Show', @pin %> |
<%= link_to 'Back', pins_path %>

app/views/pins/index.html.erb
<%= render 'pages/home' %>

<div id="pins">
  <%= render @pins %>
</div>

<%= will_paginate @pins %>



			

app/views/pins/index.js.erb
$boxes = $('<%= j render(@pins) %>')

$('#pins').append( $boxes ).imagesLoaded( function(){
  $('#pins').masonry( 'reload');
});
<% if @pins.next_page %>
  $('.pagination').replaceWith('<%= j will_paginate(@pins) %>');
<% else %>
  $('.pagination').remove();
<% end %>

app/views/pins/index_user.html.erb
<%= render 'pages/home' %>

<div id="pins">
  <%= render @pins %>
</div>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render 'form' %>

<%= link_to 'Back', pins_path %>

app/views/pins/show.html.erb
<div class="row">
	<div class="span6 offset3">
		<div class="well">
			<%= image_tag @pin.image %>
	    <p>
	     	<%= @pin.description %>
	    </p>
	    <p>
	     	<%= @pin.created_at %>
	    </p>
	     <p>
	      <%= @pin.user.name%> | User:
	     	<%= @pin.user.id%>
	    </p>
			<% if current_user == @pin.user %>
				</br>
				  <p>
		    <%= link_to 'Edit', edit_pin_path(@pin) %> |
				<%= link_to 'Back', pins_path %>
			<%else%>
        <%= link_to 'Back', pins_path %>
      <%end%>
    </div>
  </div>
</div>

app/views/user/show.html.erb
<h1><%= @user.name %></h1>

<div id="pins">
  <%= render @pins %>
</div>

<%= will_paginate @pins %>